COMPOSE := docker compose
BOT_RUN := $(COMPOSE) run --rm bot

.PHONY: help up down restart build ps logs logs-bot shell lint test licenses \
	migrate migrate-down migration revision dbshell

help:
	@printf "%s\n" \
		"make build                  Rebuild the bot image" \
		"make logs                   Follow logs for all services" \
		"make logs-bot               Follow logs for the bot service" \
		"make shell                  Open a shell inside the bot container" \
		"make lint                   Run pylint for the application code" \
		"make test                   Run pytest for the application code" \
		"make licenses               Generate LICENSES.md for direct Python dependencies" \
		"make migrate                Apply Alembic migrations to head" \
		"make migrate-down           Roll back one Alembic revision" \
		"make migration m='desc'     Create an autogenerated migration" \
		"make dbshell                Open a psql shell in the postgres container"

build:
	$(COMPOSE) build bot --no-cache

logs:
	$(COMPOSE) logs --tail=100

logs-bot:
	$(COMPOSE) logs bot --tail=100

shell:
	$(BOT_RUN) bash

lint:
	$(COMPOSE) run --rm -e PYLINTHOME=/tmp/pylint bot pylint app

test:
	$(COMPOSE) run --rm bot pytest

licenses:
	$(COMPOSE) run --rm bot sh /app/scripts/generate_licenses.sh

migrate:
	$(BOT_RUN) alembic upgrade head

migrate-down:
	$(BOT_RUN) alembic downgrade -1

migration:
ifndef m
	$(error Usage: make migration m="short description")
endif
	$(BOT_RUN) alembic revision --autogenerate -m "$(m)"

dbshell:
	$(COMPOSE) exec postgres psql -U $$POSTGRES_USER -d $$POSTGRES_DB
